export const LOAD_EMAIL = 'LOAD_EMAIL';
export const LOAD_SUBPAGE = 'LOAD_SUBPAGE';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTIONS = 'DELETE_TRANSACTIONS';
export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS';
export const LOAD_ACCOUNTS = 'LOAD_ACCOUNTS';
